import {
  Bell,
  BookOpen,
  Building,
  Calendar,
  Clock,
  Coffee,
  FileText,
  GraduationCap,
  Info,
  Library,
  MapPin,
  Mic,
  Music,
  ParkingSquare,
  Phone,
  Mail,
  ScrollText,
  Trophy,
  Users,
  Wifi,
} from "lucide-react-native";
import type { LucideIcon } from "lucide-react-native";

export const ICON_MAP: Record<string, LucideIcon> = {
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "scroll-text": ScrollText,
  info: Info,
  music: Music,
  calendar: Calendar,
  "map-pin": MapPin,
  clock: Clock,
  users: Users,
  trophy: Trophy,
  bell: Bell,
  "file-text": FileText,
  building: Building,
  mic: Mic,
  library: Library,
  coffee: Coffee,
  wifi: Wifi,
  parking: ParkingSquare,
  phone: Phone,
  mail: Mail,
};
