#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"
STRAPI_ENV_FILE="${STRAPI_ENV_FILE:-$ROOT_DIR/apps/strapi/.env}"
BACKUP_DIR="${BACKUP_DIR:-$ROOT_DIR/backups}"
PROJECT_NAME="${COMPOSE_PROJECT_NAME:-myd17}"
COMPOSE=(docker compose --project-name "$PROJECT_NAME" --env-file "$ENV_FILE" -f "$ROOT_DIR/compose.yaml")
REQUIRED_ENV=(
  APP_KEYS API_TOKEN_SALT ADMIN_JWT_SECRET TRANSFER_TOKEN_SALT JWT_SECRET
  ENCRYPTION_KEY DATABASE_NAME DATABASE_USERNAME DATABASE_PASSWORD
  STRAPI_ADMIN_PASSWORD STRAPI_EMPLOYEE_PASSWORD
)

usage() {
  cat <<'EOF'
Usage: scripts/onprem.sh <command>

Commands:
  init          Generate a production .env with random secrets
  up            Start PostgreSQL and Strapi
  down          Stop the stack
  restart       Restart Strapi
  migrate       Backup DB, pull image and restart Strapi so schema changes apply
  verify        Check secrets, backup readiness and running Strapi health
  backup        Dump PostgreSQL to backups/
  restore FILE  Restore PostgreSQL dump created by backup
  logs [svc]    Follow logs (all services or one service)
  status        Show compose status

Env overrides:
  ENV_FILE=/path/to/.env
  STRAPI_ENV_FILE=/path/to/apps/strapi/.env
  BACKUP_DIR=/path/to/backups
  STRAPI_IMAGE=ghcr.io/stawex-team/myd17/strapi:tag
EOF
}

secret() {
  openssl rand -base64 32 | tr -d '\n'
}

password() {
  printf 'A1%s' "$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | cut -c1-22)"
}

fail() {
  echo "$1" >&2
  exit 1
}

generate_env() {
  if [[ -f "$ENV_FILE" && "${FORCE:-0}" != "1" ]]; then
    echo "$ENV_FILE already exists. Set FORCE=1 to overwrite."
    exit 1
  fi

  mkdir -p "$(dirname "$ENV_FILE")"
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/onprem.sh init. Keep this file outside git and restrict access.
HOST=0.0.0.0
PORT=1337
NODE_ENV=production
STRAPI_IMAGE=${STRAPI_IMAGE:-ghcr.io/stawex-team/myd17/strapi:latest}

APP_KEYS=$(secret),$(secret),$(secret),$(secret)
API_TOKEN_SALT=$(secret)
ADMIN_JWT_SECRET=$(secret)
TRANSFER_TOKEN_SALT=$(secret)
JWT_SECRET=$(secret)
ENCRYPTION_KEY=$(secret)

STRAPI_ADMIN_PASSWORD=$(password)
STRAPI_EMPLOYEE_PASSWORD=$(password)

DATABASE_CLIENT=postgres
DATABASE_HOST=database
DATABASE_PORT=5432
DATABASE_NAME=myd17
DATABASE_USERNAME=myd17
DATABASE_PASSWORD=$(password)
DATABASE_SSL=false
EOF

  chmod 600 "$ENV_FILE"

  local linked_strapi_env=0
  if [[ "$STRAPI_ENV_FILE" != "$ENV_FILE" ]]; then
    mkdir -p "$(dirname "$STRAPI_ENV_FILE")"
    rm -f "$STRAPI_ENV_FILE"
    ln -s "$(realpath --relative-to="$(dirname "$STRAPI_ENV_FILE")" "$ENV_FILE" 2>/dev/null || printf '%s' "$ENV_FILE")" "$STRAPI_ENV_FILE"
    linked_strapi_env=1
  fi

  echo "Created $ENV_FILE with mode 600."
  if [[ "$linked_strapi_env" -eq 1 ]]; then
    echo "Linked $STRAPI_ENV_FILE to $ENV_FILE."
  fi
  echo "Store a secure copy of this file before starting production."
}

env_value() {
  local key="$1"
  awk -F '=' -v key="$key" '$1 == key { sub(/^[^=]*=/, ""); value = $0 } END { print value }' "$ENV_FILE"
}

file_mode() {
  stat -c "%a" "$1" 2>/dev/null || stat -f "%Lp" "$1" 2>/dev/null
}

looks_like_placeholder() {
  local lower
  lower="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')"

  case "$lower" in
    ""|password|username|secret|*_secret|change-me*|*change_me*|*changeme*|your_*|example*)
      return 0
      ;;
  esac

  return 1
}

require_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    fail "Missing $ENV_FILE. Run: scripts/onprem.sh init"
  fi

  for key in "${REQUIRED_ENV[@]}"; do
    if [[ -z "$(env_value "$key")" ]]; then
      fail "Missing required env value: $key"
    fi
  done
}

validate_env_file() {
  local issues=0
  local mode
  mode="$(file_mode "$ENV_FILE")"

  if [[ -z "$mode" ]]; then
    echo "Warning: could not read file permissions for $ENV_FILE" >&2
    issues=$((issues + 1))
  elif (( (8#$mode & 8#077) != 0 )); then
    echo "Warning: $ENV_FILE is readable by group or others. Run: chmod 600 $ENV_FILE" >&2
    issues=$((issues + 1))
  fi

  if [[ "$(env_value NODE_ENV)" != "production" ]]; then
    echo "Warning: NODE_ENV should be set to production in $ENV_FILE" >&2
    issues=$((issues + 1))
  fi

  local key value
  for key in "${REQUIRED_ENV[@]}"; do
    value="$(env_value "$key")"
    if looks_like_placeholder "$value"; then
      echo "Warning: replace placeholder value for $key in $ENV_FILE" >&2
      issues=$((issues + 1))
    fi
  done

  local app_keys
  IFS=',' read -r -a app_keys <<<"$(env_value APP_KEYS)"
  if [[ "${#app_keys[@]}" -lt 2 ]]; then
    echo "Warning: APP_KEYS should contain at least two comma-separated keys" >&2
    issues=$((issues + 1))
  fi

  for key in "${app_keys[@]}"; do
    if [[ "${#key}" -lt 32 ]]; then
      echo "Warning: each APP_KEYS entry should be at least 32 characters" >&2
      issues=$((issues + 1))
      break
    fi
  done

  for key in API_TOKEN_SALT ADMIN_JWT_SECRET TRANSFER_TOKEN_SALT JWT_SECRET ENCRYPTION_KEY; do
    value="$(env_value "$key")"
    if [[ "${#value}" -lt 32 ]]; then
      echo "Warning: $key should be at least 32 characters" >&2
      issues=$((issues + 1))
    fi
  done

  for key in STRAPI_ADMIN_PASSWORD STRAPI_EMPLOYEE_PASSWORD DATABASE_PASSWORD; do
    value="$(env_value "$key")"
    if [[ "${#value}" -lt 12 ]]; then
      echo "Warning: $key should be at least 12 characters" >&2
      issues=$((issues + 1))
    fi
  done

  if [[ "$issues" -ne 0 ]]; then
    echo "Warning: environment verification found $issues issue(s)." >&2
  fi
}

wait_for_db() {
  local db_user db_name
  db_user="$(env_value DATABASE_USERNAME)"
  db_name="$(env_value DATABASE_NAME)"

  for _ in {1..30}; do
    if "${COMPOSE[@]}" exec -T database pg_isready -U "$db_user" -d "$db_name" >/dev/null 2>&1; then
      return
    fi
    sleep 2
  done

  echo "PostgreSQL did not become ready in time."
  exit 1
}

verify_backup_readiness() {
  local db_user db_name
  db_user="$(env_value DATABASE_USERNAME)"
  db_name="$(env_value DATABASE_NAME)"

  "${COMPOSE[@]}" up -d database
  wait_for_db
  "${COMPOSE[@]}" exec -T database pg_dump -U "$db_user" -d "$db_name" --schema-only --no-owner --no-acl >/dev/null
  echo "Database backup pre-check passed."
}

verify_strapi_health() {
  if ! "${COMPOSE[@]}" exec -T strapi wget -qO- http://localhost:1337/_health >/dev/null; then
    fail "Strapi healthcheck failed"
  fi

  echo "Strapi healthcheck passed."
}

start_stack() {
  require_env
  validate_env_file
  "${COMPOSE[@]}" --profile prod up -d
}

backup_db() {
  require_env
  validate_env_file
  mkdir -p "$BACKUP_DIR"
  local db_user db_name output
  db_user="$(env_value DATABASE_USERNAME)"
  db_name="$(env_value DATABASE_NAME)"
  output="$BACKUP_DIR/${PROJECT_NAME}-$(date +%Y%m%d-%H%M%S).dump"

  "${COMPOSE[@]}" up -d database
  wait_for_db
  "${COMPOSE[@]}" exec -T database pg_dump -U "$db_user" -d "$db_name" --format=custom --no-owner --no-acl >"$output"
  if [[ ! -s "$output" ]]; then
    rm -f "$output"
    fail "Backup failed: dump file is empty."
  fi

  if ! "${COMPOSE[@]}" exec -T database pg_restore --list <"$output" >/dev/null; then
    rm -f "$output"
    fail "Backup failed: dump file could not be read by pg_restore."
  fi

  chmod 600 "$output"
  echo "Backup saved to $output"
}

restore_db() {
  require_env
  local input="${1:-}"
  if [[ -z "$input" || ! -f "$input" ]]; then
    echo "Usage: scripts/onprem.sh restore FILE"
    exit 1
  fi

  local db_user db_name
  db_user="$(env_value DATABASE_USERNAME)"
  db_name="$(env_value DATABASE_NAME)"

  "${COMPOSE[@]}" stop strapi >/dev/null 2>&1 || true
  "${COMPOSE[@]}" up -d database
  wait_for_db
  backup_db
  "${COMPOSE[@]}" exec -T database pg_restore -U "$db_user" -d "$db_name" --clean --if-exists --no-owner --no-acl <"$input"
  "${COMPOSE[@]}" --profile prod up -d strapi
  echo "Restored $input"
}

migrate_stack() {
  require_env
  backup_db
  
  local strapi_image
  strapi_image="$(env_value STRAPI_IMAGE)"
  
  # Only pull if image is from a registry (contains /)
  if [[ "$strapi_image" == */* ]]; then
    "${COMPOSE[@]}" --profile prod pull strapi
  fi
  
  "${COMPOSE[@]}" --profile prod up -d
  echo "Strapi restarted. Application schema changes run during Strapi startup."
}

verify_stack() {
  require_env
  validate_env_file
  "${COMPOSE[@]}" config --quiet
  verify_backup_readiness
  verify_strapi_health
  echo "Verification passed: migration backup readiness and Strapi health are OK."
}

case "${1:-}" in
  init)
    generate_env
    ;;
  up)
    start_stack
    ;;
  down)
    require_env
    "${COMPOSE[@]}" --profile prod down
    ;;
  restart)
    require_env
    "${COMPOSE[@]}" --profile prod restart strapi
    ;;
  migrate)
    migrate_stack
    ;;
  verify)
    verify_stack
    ;;
  backup)
    backup_db
    ;;
  restore)
    restore_db "${2:-}"
    ;;
  logs)
    require_env
    if [[ -n "${2:-}" ]]; then
      "${COMPOSE[@]}" --profile prod logs -f "$2"
    else
      "${COMPOSE[@]}" --profile prod logs -f
    fi
    ;;
  status)
    require_env
    "${COMPOSE[@]}" --profile prod ps
    ;;
  ""|-h|--help|help)
    usage
    ;;
  *)
    echo "Unknown command: $1"
    usage
    exit 1
    ;;
esac
