#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"
BACKUP_DIR="${BACKUP_DIR:-$ROOT_DIR/backups}"
PROJECT_NAME="${COMPOSE_PROJECT_NAME:-myd17}"
COMPOSE=(docker compose --project-name "$PROJECT_NAME" --env-file "$ENV_FILE" -f "$ROOT_DIR/compose.yaml")

usage() {
  cat <<'EOF'
Usage: scripts/onprem.sh <command>

Commands:
  init          Generate a production .env with random secrets
  up            Start PostgreSQL and Strapi
  down          Stop the stack
  restart       Restart Strapi
  migrate       Backup DB, pull image and restart Strapi so schema changes apply
  backup        Dump PostgreSQL to backups/
  restore FILE  Restore PostgreSQL dump created by backup
  logs [svc]    Follow logs (all services or one service)
  status        Show compose status

Env overrides:
  ENV_FILE=/path/to/.env
  BACKUP_DIR=/path/to/backups
  STRAPI_IMAGE=ghcr.io/stawex-team/myd17/strapi:tag
EOF
}

secret() {
  openssl rand -base64 32 | tr -d '\n'
}

password() {
  openssl rand -hex 18 | cut -c1-24
}

generate_env() {
  if [[ -f "$ENV_FILE" && "${FORCE:-0}" != "1" ]]; then
    echo "$ENV_FILE already exists. Set FORCE=1 to overwrite."
    exit 1
  fi

  mkdir -p "$(dirname "$ENV_FILE")"
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/onprem.sh init. Keep this file outside git and restrict access.
HOST=0.0.0.0
PORT=1337
NODE_ENV=production
STRAPI_IMAGE=${STRAPI_IMAGE:-ghcr.io/stawex-team/myd17/strapi:latest}

APP_KEYS=$(secret),$(secret),$(secret),$(secret)
API_TOKEN_SALT=$(secret)
ADMIN_JWT_SECRET=$(secret)
TRANSFER_TOKEN_SALT=$(secret)
JWT_SECRET=$(secret)
ENCRYPTION_KEY=$(secret)

STRAPI_SUPERADMIN_PASSWORD=$(password)
STRAPI_ADMIN_PASSWORD=$(password)
STRAPI_EDITOR_PASSWORD=$(password)

DATABASE_CLIENT=postgres
DATABASE_HOST=database
DATABASE_PORT=5432
DATABASE_NAME=myd17
DATABASE_USERNAME=myd17
DATABASE_PASSWORD=$(password)
DATABASE_SSL=false
EOF

  chmod 600 "$ENV_FILE"
  echo "Created $ENV_FILE with mode 600."
  echo "Store a secure copy of this file before starting production."
}

env_value() {
  local key="$1"
  awk -F '=' -v key="$key" '$1 == key { sub(/^[^=]*=/, ""); value = $0 } END { print value }' "$ENV_FILE"
}

require_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Missing $ENV_FILE. Run: scripts/onprem.sh init"
    exit 1
  fi

  local required=(
    APP_KEYS API_TOKEN_SALT ADMIN_JWT_SECRET TRANSFER_TOKEN_SALT JWT_SECRET
    ENCRYPTION_KEY DATABASE_NAME DATABASE_USERNAME DATABASE_PASSWORD
  )

  for key in "${required[@]}"; do
    if [[ -z "$(env_value "$key")" ]]; then
      echo "Missing required env value: $key"
      exit 1
    fi
  done
}

wait_for_db() {
  local db_user db_name
  db_user="$(env_value DATABASE_USERNAME)"
  db_name="$(env_value DATABASE_NAME)"

  for _ in {1..30}; do
    if "${COMPOSE[@]}" exec -T database pg_isready -U "$db_user" -d "$db_name" >/dev/null 2>&1; then
      return
    fi
    sleep 2
  done

  echo "PostgreSQL did not become ready in time."
  exit 1
}

start_stack() {
  require_env
  "${COMPOSE[@]}" --profile prod up -d
}

backup_db() {
  require_env
  mkdir -p "$BACKUP_DIR"
  local db_user db_name output
  db_user="$(env_value DATABASE_USERNAME)"
  db_name="$(env_value DATABASE_NAME)"
  output="$BACKUP_DIR/${PROJECT_NAME}-$(date +%Y%m%d-%H%M%S).dump"

  "${COMPOSE[@]}" up -d database
  wait_for_db
  "${COMPOSE[@]}" exec -T database pg_dump -U "$db_user" -d "$db_name" --format=custom --no-owner --no-acl >"$output"
  chmod 600 "$output"
  echo "Backup saved to $output"
}

restore_db() {
  require_env
  local input="${1:-}"
  if [[ -z "$input" || ! -f "$input" ]]; then
    echo "Usage: scripts/onprem.sh restore FILE"
    exit 1
  fi

  local db_user db_name
  db_user="$(env_value DATABASE_USERNAME)"
  db_name="$(env_value DATABASE_NAME)"

  "${COMPOSE[@]}" stop strapi >/dev/null 2>&1 || true
  "${COMPOSE[@]}" up -d database
  wait_for_db
  backup_db
  "${COMPOSE[@]}" exec -T database pg_restore -U "$db_user" -d "$db_name" --clean --if-exists --no-owner --no-acl <"$input"
  "${COMPOSE[@]}" --profile prod up -d strapi
  echo "Restored $input"
}

migrate_stack() {
  require_env
  backup_db
  "${COMPOSE[@]}" --profile prod pull strapi
  "${COMPOSE[@]}" --profile prod up -d
  echo "Strapi restarted. Application schema changes run during Strapi startup."
}

case "${1:-}" in
  init)
    generate_env
    ;;
  up)
    start_stack
    ;;
  down)
    require_env
    "${COMPOSE[@]}" --profile prod down
    ;;
  restart)
    require_env
    "${COMPOSE[@]}" --profile prod restart strapi
    ;;
  migrate)
    migrate_stack
    ;;
  backup)
    backup_db
    ;;
  restore)
    restore_db "${2:-}"
    ;;
  logs)
    require_env
    if [[ -n "${2:-}" ]]; then
      "${COMPOSE[@]}" --profile prod logs -f "$2"
    else
      "${COMPOSE[@]}" --profile prod logs -f
    fi
    ;;
  status)
    require_env
    "${COMPOSE[@]}" --profile prod ps
    ;;
  ""|-h|--help|help)
    usage
    ;;
  *)
    echo "Unknown command: $1"
    usage
    exit 1
    ;;
esac
